# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: rakenhammed/image_processor:image_processor
      -
        name: Download project as artifact
        uses: actions/upload-artifact@main
        with:
          name: bundle
          path: ./imageProcessor
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - 
        name: Download artifact
        uses: actions/download-artifact@main
        with:
          name: bundle
          path: ./imageProcessor
      - 
        name: Deploy project with SSH
        uses: easingthemes/ssh-deploy@v2.1.4
        env:
         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
         REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
         REMOTE_USER: ${{ secrets.REMOTE_USER }}
         SOURCE: "imageProcessor"
         TARGET: "~/"
  
